services:
  db:
    container_name: db-1
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sunwindscada-network

  django:
    container_name: django-1
    build:
      context: .
      dockerfile: Dockerfile.django
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - sunwindscada-network

  dash:
    container_name: dash-1
    build:
      context: ./dash_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - django
    volumes:
      - ./dash_frontend:/app
      - .:/app/backend  # Mount the backend code for API access
    networks:
      - sunwindscada-network

networks:
  sunwindscada-network:
    name: sunwindscada

volumes:
  postgres_data:
