version: '3.9'

services:
  reflex:
    container_name: reflex-1
    build:
      context: .
      dockerfile: Dockerfile.reflex
    environment:
      - REFLEX_API_URL=http://django-1:8000/api
      - REFLEX_DB_URL=postgresql://scada_user:scada_password@db-1:5432/scada_db
      - REFLEX_ENV=production
    ports:
      - "3000:3000"
    networks:
      - sunwindscada
    command: python -m reflex run --host 0.0.0.0 --frontend-port 3000 --backend-port 8000 --app reflex_frontend.app

networks:
  sunwindscada:
    external: true
